### ISSUE TITLE
I can't seem to add your module

### ISSUE THREAD

**Issue by amanofscience** [VansonLeung/react-native-keyboard-aware-view#4]
Every time I try and run your project I get this error.
# 

Facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: Seems you're trying to access 'ReactNative.Component' from the 'react-native' package. Perhaps you meant to access 'React.Component' from the 'react' package instead?

For example, instead of:

  import React, { Component, View } from 'react-native';

You should now do:

  import React, { Component } from 'react';
#   import { View } from 'react-native';

What's the latest version of react-native that this module supports?

**Comment by VansonLeung** [comment]
Fixed, thanks
