### ISSUE TITLE
keyboardWillShow and keyboardWillHide should be registered via Keyboard module

### ISSUE THREAD

**Issue by amanofscience** [VansonLeung/react-native-keyboard-aware-view#5]
I'm getting this warning:

keyboardWillShow and keyboardWillHide should be registered via Keyboard module

DeviceEventEmitter is deprecated and needs to be replaced with Keyboard

**Comment by VansonLeung** [comment]
What React Native Version are you using?

**Comment by amanofscience** [comment]
0.29
