### ISSUE TITLE
How does this library compare to APSL/react-native-keyboard-aware-scroll-view?

### ISSUE THREAD

**Issue by joonhocho** [VansonLeung/react-native-keyboard-aware-view#6]
Hey, great work! 
I am looking into keyboard aware scroll views.
I wonder if you created this repo because you thought something was missing with [APSL/react-native-keyboard-aware-scroll-view](https://github.com/APSL/react-native-keyboard-aware-scroll-view).

**Comment by VansonLeung** [comment]
This plugin is a simple React Native View component that resizes composite children views inside itself when the keyboard appears. You can implement your own ScrollView, ListView, Multiple Views etc... inside the View and set your own view to 'flex: 1'.

APSL/react-native-keyboard-aware-scroll-view   is an implementation of `<ScrollView>`, 
while mine is just an implementation of `<View>`. 

Why I created this repo:
This plugin is a more abstract attempt actually inspired by APSL/react-native-keyboard-aware-scroll-view. In my case, I had to add a sticky bottom bar `<View>` for a Submit Button between the `<ScrollView>` and the Keyboard (refer to the README's Gif).

APSL/react-native-keyboard-aware-scroll-view is wrapped with `<ScrollView>` and does not let me do the sticky view things. Therefore, I decided to roll out my own attempt to do the following hierarchy:

```
<KeyboardAwareView>
  {/* Scroll View */}
  <View style={{flex: 1, alignItems: 'stretch'}}>
    <ScrollView style={{flex: 1}}>
        ....
    </ScrollView>
  </View>

  {/* Sticky View */}
  <View style={{height: 48, alignItems: 'stretch'}}>
      <TouchableOpacity ... />
  </View>
</KeyboardAwareView>
```

**Comment by joonhocho** [comment]
Awesome! Thanks for your explanation!
